import express from "express";
import {register,login,logout,currentUser,verifyEmail} from "../controller/auth_controller.js";
import authMiddleware from "../middleware/auth_middleware.js";
const router = express.Router();
router.post("/register", register);
router.post("/login", login);
router.get("/verify/:token", verifyEmail);
router.post("/logout", authMiddleware, logout);
router.get("/currentUser", authMiddleware, currentUser);
export default router;